name: Shelvd CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    # only run actions when backend or actions file are updated
    paths: 
      - 'server/**'
      - '.github/workflows/**'
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install MongoDB
        uses: supercharge/mongodb-github-action@1.8.0

      - name: Install Node Packages
        working-directory: ./server
        run: npm install

      - name: Setup .env
        working-directory: ./server
        run: |
          echo "CLOUD_STRING=${{ secrets.CLOUD_STRING }}" >> .env
          echo "CLOUD_MONGO=0" >> .env 
          echo "CLOUD_STRING=${{ secrets.ARGON2_SECRET }}" >> .env

      - name: Run Tests
        working-directory: ./server
        run: npm run test
